name: CodeMapRT CI & Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  select-and-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Build HTML report
        run: python -m codemaprt.cli --changed-files .codemaprt/changed_files.txt --report reports/index.html
      - run: pytest -q
      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: codemaprt-report
          path: reports/index.html

  build-gifs:
    runs-on: ubuntu-latest
    needs: select-and-report
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pillow imageio pyyaml
      - name: Download report artifact
        uses: actions/download-artifact@v4
        with:
          name: codemaprt-report
          path: reports
      - name: Build GIF/PNG from report
        run: python tools/make_full_gifs.py
      - name: Upload GIF/PNG artifacts
        uses: actions/upload-artifact@v4
        with:
          name: codemaprt-gifs
          path: |
            assets/demo.gif
            assets/CodeMapRT_Table_Full_1-33.png

  build-pages:
    runs-on: ubuntu-latest
    needs: [select-and-report, build-gifs]
    steps:
      - uses: actions/checkout@v4
      - name: Download report artifact
        uses: actions/download-artifact@v4
        with:
          name: codemaprt-report
          path: public
      - name: Download gifs artifact
        uses: actions/download-artifact@v4
        with:
          name: codemaprt-gifs
          path: public/assets
      - name: Build landing page
        run: |
          mv public/index.html public/report.html || true
          echo '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CodeMapRT — Demo</title><style>body{font-family:Arial,Helvetica,sans-serif;max-width:1100px;margin:40px auto;padding:0 16px;line-height:1.5}img{max-width:100%;height:auto}</style></head><body><h1>CodeMapRT — Demo</h1><p>This page is published automatically from GitHub Actions. It embeds the scrolling GIF and links to the full HTML report.</p><p><img src="assets/demo.gif" alt="CodeMapRT demo GIF"></p><p><a href="report.html">Open full HTML report</a> • <a href="assets/CodeMapRT_Table_Full_1-33.png">PNG table</a></p></body></html>' > public/index.html
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy-pages:
    runs-on: ubuntu-latest
    needs: build-pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
